version: 0.0
os: linux

hooks:
  ApplicationStop:
    - script: |
        #!/bin/bash
        set -e

        echo "Stopping container..."
        # Get the container ID of the running container
        container_id=$(docker ps | awk 'NR==2 {print $1}')

        # Remove the existing container if it exists
        if [ -n "$container_id" ]; then
          docker rm -f $container_id
        else
          echo "No running container found."
        fi
      timeout: 300
      runas: root
  AfterInstall:
    - script: |
        #!/bin/bash
        set -e

        echo "Pulling the Docker image from Docker Hub..."
        docker pull keerthid2001/simple-python-flask-app:latest

        echo "Running the Docker image as a container..."
        docker run -d -p 5000:5000 --name my_container keerthid2001/simple-python-flask-app:latest
      timeout: 300
      runas: root
